import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { loadCatalogue, ontologyRoot as root } from '../catalogue.mjs';
const noknokRoot = resolve(root, '../../NokNok');
const catalogue = loadCatalogue();
// Bundle canonical service artwork for offline profile rendering on every client.
for (const service of catalogue.nodes['S:T:SV'].Records) {
  service.iconSvg = readFileSync(resolve(root, '_support/service-icons', `${service.id}.svg`), 'utf8');
}
const out = resolve(noknokRoot, 'shared/ontology-catalogue.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by Ontology/_support/tools/build.mjs. Edit the ontology tree.\n(function(r){const c=${JSON.stringify(
    catalogue,
  )};if(typeof module==='object')module.exports=c;else r.NokNokCatalogue=c;})(globalThis);\n`,
);
console.log(
  `Validated ${Object.keys(catalogue.nodes).length} ontology nodes and ${
    Object.keys(catalogue.collections).length
  } collections.`,
);

// Generate the Mobile document from original JS, before Metro can rewrite function bodies.
const require = createRequire(resolve(noknokRoot, 'package.json'));
const editor = require('./shared/data-editor.js');
const engine = require('./shared/data-slices.js');
const { errorPresentation } = require('./shared/error-presentation.js');
writeFileSync(
  resolve(noknokRoot, 'shared/data-editor-document.js'),
  'module.exports = ' +
    JSON.stringify(editor.documentHTML(catalogue, engine, errorPresentation)) +
    ';\n',
);

const contactRequest = require('./shared/contact-request.js');
writeFileSync(resolve(noknokRoot, 'shared/contact-request-document.js'), 'module.exports = ' + JSON.stringify(contactRequest.documentHTML(catalogue,engine,require('./shared/contact-query.js'),editor.css,errorPresentation)) + ';\n');
