import { createRequire } from 'node:module';
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  realpathSync,
  readdirSync,
} from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const noknokRoot = resolve(root, '../../NokNok');
const nodes = {},
  visited = new Set();
function visit(file, code = '') {
  file = realpathSync(file);
  if (!file.startsWith(root + '/') || visited.has(file))
    throw Error(`Repeated or escaping reference: ${file}`);
  visited.add(file);
  const node = JSON.parse(readFileSync(file, 'utf8'));
  if (!node.Name || typeof node.Name !== 'string')
    throw Error(`Missing Name: ${file}`);
  if ('Kind' in node || 'Code' in node)
    throw Error(`Codes come from paths, not ${file}`);
  for (const key of ['Public', 'PublicRequired', 'PrivateRequired', 'SubjectType'])
    if (key in node && typeof node[key] !== 'boolean') throw Error(`Invalid ${key}: ${file}`);
  if ('Scalar' in node && typeof node.Scalar !== 'boolean')
    throw Error(`Scalar must be boolean: ${file}`);
  nodes[code] = { ...node, Code: code };
  if (node.Children) {
    nodes[code].Children = {};
    for (const [key, ref] of Object.entries(node.Children)) {
      if (
        !/^[A-Z][A-Z0-9]*$/.test(key) ||
        Object.keys(ref).join() !== '$ref' ||
        !ref.$ref.startsWith('./')
      )
        throw Error(`Invalid child in ${file}`);
      const child = code ? `${code}:${key}` : key;
      nodes[code].Children[key] = child;
      visit(resolve(dirname(file), ref.$ref), child);
    }
  }
}
visit(resolve(root, 'index.json'));
for (const node of Object.values(nodes)) {
  if (
    node.ValueType &&
    !['string', 'integer', 'number', 'boolean'].includes(node.ValueType)
  )
    throw Error(`Invalid primitive: ${node.Code}`);
  if (
    typeof node.Scalar === 'boolean' &&
    (!Array.isArray(node.Subjects) ||
      !node.Subjects.length ||
      node.Subjects.some((s) => !nodes[s]?.SubjectType) ||
      Object.values(node.Children || {}).some((code) => !nodes[code]?.Type))
  )
    throw Error(`Invalid answer object: ${node.Code}`);
  if (node.Type && !nodes[node.Type]?.ValueType)
    throw Error(`Unknown value type: ${node.Code}`);
  if (node.Type && !node.Question)
    throw Error(`Missing question: ${node.Code}`);
  if (
    node.Type &&
    !('Scalar' in nodes[node.Code.split(':').slice(0, -1).join(':')])
  )
    throw Error(`Answer outside object: ${node.Code}`);
  if (node.DisplayFormat !== undefined) {
    if (typeof node.DisplayFormat !== 'string' || typeof node.Scalar !== 'boolean') throw Error(`Invalid DisplayFormat: ${node.Code}`);
    for (const match of node.DisplayFormat.matchAll(/\{([^}]+)\}/g)) if (!node.Children?.[match[1]]) throw Error(`Unknown DisplayFormat field: ${node.Code}:${match[1]}`);
    if (node.DisplayOmitValues && Object.entries(node.DisplayOmitValues).some(([key, values]) => !node.Children?.[key] || !Array.isArray(values) || values.some(value => typeof value !== 'string'))) throw Error(`Invalid DisplayOmitValues: ${node.Code}`);
  }
  if (node.AllowCustom !== undefined && (node.AllowCustom !== true || nodes[node.Type]?.ValueType !== 'string' || !node.Choices?.includes(node.CustomChoice))) throw Error(`Invalid custom choice: ${node.Code}`);
  if (node.ChoiceAliases && Object.values(node.ChoiceAliases).some(value => !node.Choices?.includes(value))) throw Error(`Invalid choice alias: ${node.Code}`);
  if (node.Pattern) new RegExp(node.Pattern);
}
const collections = JSON.parse(
  readFileSync(resolve(root, '_support/collections/index.json')),
);
for (const collection of Object.values(collections))
  for (const code of collection.Fields)
    if (!nodes[code]?.Type) throw Error(`Unknown collection field: ${code}`);
function checkOrphans(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      if (p !== resolve(root, '_support') && !entry.name.startsWith('.'))
        checkOrphans(p);
    } else if (
      entry.name.endsWith('.json') &&
      !visited.has(realpathSync(p))
    )
      throw Error(`Unreachable definition: ${relative(root, p)}`);
  }
}
checkOrphans(root);
const migrations = Object.fromEntries(readdirSync(resolve(root, '_support/migrations')).filter(f => f.endsWith('.json')).map(f => [f.slice(0, -5), JSON.parse(readFileSync(resolve(root, '_support/migrations', f), 'utf8'))]));
const catalogue = { version: nodes[''].Version, nodes, collections, migrations };
const out = resolve(noknokRoot, 'shared/ontology-catalogue.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by Ontology/_support/tools/build.mjs. Edit the ontology tree.\n(function(r){const c=${JSON.stringify(
    catalogue,
  )};if(typeof module==='object')module.exports=c;else r.NokNokCatalogue=c;})(globalThis);\n`,
);
console.log(
  `Validated ${visited.size} ontology nodes and ${
    Object.keys(collections).length
  } collections.`,
);

// Generate the Mobile document from original JS, before Metro can rewrite function bodies.
const require = createRequire(resolve(noknokRoot, 'package.json'));
const editor = require('./shared/data-editor.js');
const engine = require('./shared/data-slices.js');
const { errorPresentation } = require('./shared/error-presentation.js');
writeFileSync(
  resolve(noknokRoot, 'shared/data-editor-document.js'),
  'module.exports = ' +
    JSON.stringify(editor.documentHTML(catalogue, engine, errorPresentation)) +
    ';\n',
);

const contactRequest = require('./shared/contact-request.js');
writeFileSync(resolve(noknokRoot, 'shared/contact-request-document.js'), 'module.exports = ' + JSON.stringify(contactRequest.documentHTML(catalogue,engine,require('./shared/contact-query.js'),editor.css,errorPresentation)) + ';\n');
